{% set name = "scspell3k" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scspell3k-{{ version }}.tar.gz
  sha256: fbe1131593ff0de5dc2cb7cfe2353152e2c82dedba4d3e9316eb58357e855d04

build:
  entry_points:
    - scspell = scspell:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - scspell
  commands:
    - pip check
    - scspell --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/myint/scspell
  summary: A conservative interactive spell checker for source code.
  license: GPL-2.0-only
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - thewchan
